force-app/main/default/objects/Order__c/Order__c.object-meta.xml
<CustomObject>
    <label>Order</label>
    <nameField>
        <displayFormat>O-{00000}</displayFormat>
        <label>Order Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Orders</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Order_Item__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Price__c.field-meta.xml
<CustomField>
    <fullName>Price__c</fullName>
    <label>Price</label>
    <precision>8</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Order Items</relationshipLabel>
    <relationshipName>Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Qty_L__c.field-meta.xml
<CustomField>
    <fullName>Qty_L__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty L</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Qty_M__c.field-meta.xml
<CustomField>
    <fullName>Qty_M__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty M</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Order_Item__c/fields/Qty_S__c.field-meta.xml
<CustomField>
    <fullName>Qty_S__c</fullName>
    <defaultValue>1</defaultValue>
    <label>Qty S</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/OrderController.cls
public with sharing class OrderController {

    @AuraEnabled(Cacheable=true)
    public static Order_Item__c[] getOrderItems(Id orderId) {
        return [SELECT Id, Product__r.Name, Product__r.MSRP__c, Product__r.Picture_URL__c, Qty_S__c, Qty_M__c, Qty_L__c, Price__c
            FROM Order_Item__c WHERE Order__c = :orderId];
    }

    @AuraEnabled
    public static void deleteOrderItem(Id orderItemId) {
        Order_Item__c orderItem = new Order_Item__c(Id = orderItemId);
        delete orderItem;
    }

}